# Generated by Django 2.2.5 on 2020-01-13 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('duration', models.CharField(max_length=10)),
                ('director', models.CharField(max_length=128)),
                ('Genre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='example.Genre')),
            ],
        ),
    ]
