# Generated by Django 2.2.5 on 2020-01-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=2000, max_length=2030),
            preserve_default=False,
        ),
    ]
